In [3]:
import os

import numpy as np
import pandas as pd

In [5]:
filePath = './data/'
savePath = './data_mvc/'
count = 0
featureArr = []
mvc = pd.read_csv('./max/max.csv', header=1).astype(float)
mvc=np.array(mvc).T
# max_0=np.max(mvc[2])
# min_0=np.min(mvc[2])
# max_1=np.max(mvc[3])
# min_1=np.min(mvc[3])
# max_2=np.max(mvc[4])
# min_2=np.min(mvc[4])
# max_3=np.max(mvc[5])
# min_3=np.min(mvc[5])
# max_4=np.max(mvc[6])
# min_4=np.min(mvc[6])
# max_5=np.max(mvc[7])
# min_5=np.min(mvc[7])
for root, dirs, files in os.walk(filePath):
    for file in files:
        path = os.path.join(root, file)
        print(path)
        sPath = savePath + path.split("/")[-2] + "/" +  file
        data = pd.read_csv(path, header=1).astype(float)
        # print(data.head())
        data = np.array(data).T
        # print(type(data[5]))
        # print(data.shape)
        
        for i in range(2, 8):
            min_val = np.min(mvc[i])
            # print(min_val)
            max_val = np.max(mvc[i])
            # print(max_val)
            range_val = max_val - min_val  # 计算范围（最大值-最小值）
            # print(range_val)
            if range_val != 0:  # 确保分母不为0
                data[i] = (data[i] - min_val) / range_val
                print(data[i])
            else:
                # 处理range_val为0的情况，例如通过设为0或保持不变
                data[i] = 0  # 或其他适当的处理方式
            # print(data[i])
        pd.DataFrame(data).T.to_csv(sPath, header=None, index=None)

./data/3/emg_left_arm_3_3.csv
[0.47389034 0.47127937 0.47650131 ... 0.46475196 0.47127937 0.47258486]
[0.41780822 0.40068493 0.41552511 ... 0.39383562 0.41780822 0.40981735]
[0.34108108 0.32162162 0.33675676 ... 0.32486486 0.33513514 0.32756757]
[0.50599169 0.5006114  0.50158963 ... 0.50085596 0.50452433 0.49523111]
[0.61648352 0.62087912 0.62527473 ... 0.62307692 0.62637363 0.62087912]
[0.43650126 0.43902439 0.43986543 ... 0.43566022 0.44154752 0.43902439]
./data/3/emg_left_arm_3_6.csv
[0.47780679 0.46475196 0.46736292 ... 0.48302872 0.47780679 0.47258486]
[0.44520548 0.40182648 0.42237443 ... 0.42465753 0.42694064 0.40753425]
[0.36540541 0.32324324 0.34594595 ... 0.35567568 0.32918919 0.33189189]
[0.50110051 0.49987772 0.50085596 ... 0.50158963 0.49792125 0.50232331]
[0.62747253 0.62307692 0.62087912 ... 0.62747253 0.62087912 0.62417582]
[0.43902439 0.43818335 0.43902439 ... 0.43902439 0.43986543 0.43650126]
./data/3/emg_left_arm_3_8.csv
[0.57441253 0.38642298 0.5691906  ... 0.494778

In [8]:
import pandas as pd
import numpy as np
# 读取数据
mvc = pd.read_csv('./max/max.csv', header=1).astype(float)
mvc=np.array(mvc).T
# 初始化列表来存储最大值和最小值
max_values = []
min_values = []

# 计算每一列的最大值和最小值
for i in range(2,8):
    max_values.append(np.max(mvc[i]))
    min_values.append(np.min(mvc[i]))

# 创建一个 DataFrame 来保存这些值
max_min_df = pd.DataFrame({
    'column': [i for i in range(6)],
    'max_value': max_values,
    'min_value': min_values
})

# 指定保存的文件路径
save_path = './max/min_max_values.csv'

# 保存到 CSV 文件
max_min_df.to_csv(save_path, index=False)

print(f"Max and min values saved to {save_path}")


Max and min values saved to ./max/min_max_values.csv
